- name: Set epoch plus client_id
  ansible.builtin.set_fact:
    eclient_id: "{{ etime }}{{ client_id }}"

- name: Use openssh to create hashmac
  ansible.builtin.shell: >
     set -o pipefail && \
     echo -n "{{ eclient_id }}" | openssl sha256 -hmac "{{ client_secret }}"
  register: hmac
  args:
    executable: /bin/bash
  changed_when: false

- name: Show ansible.builtin.debug
  ansible.builtin.debug:
    msg:
      - "{{ etime }}"
      - "{{ eclient_id }}"
      - "{{ hmac }}"
      - "{{ hmac.stdout }}"
      - "{{ hmac.stdout.split(' ')[1] }}"
    verbosity: 2

- name: Set hmac key
  ansible.builtin.set_fact:
    hmackey: "{{ hmac.stdout.split(' ')[1] }}"

- name: Get cluster status on "{{ cluster_id }}" until state is "{{ clusterstate }}"
  ansible.builtin.uri:
    url: "{{ api_url_v1 }}/clusters/{{ cluster_id }}"
    method: GET
    validate_certs: false
    body_format: json
    status_code: 200
    return_content: true
    headers:
      "X-Frame-ClientId": "{{ client_id }}"
      "X-Frame-Timestamp": "{{ etime }}"
      "X-Frame-Signature": "{{ hmackey }}"
  register: query
  until: clusterstate in query.json.cluster_state
  retries: "{{ qretries }}"
  delay: "{{ qdelay }}"

- name: Show result of query var
  ansible.builtin.debug:
    msg: "{{ query.json }}"
    verbosity: 2

- name: Show cluster status of "{{ cluster_id }}"
  ansible.builtin.debug:
    msg:
      - "Cluster name: {{ query.json.name }}"
      - "Cluster state: {{ query.json.cluster_state }}"
      - "Cluster service ip: {{ query.json.cluster_service_ip }}"

- name: Show load balancer status
  ansible.builtin.debug:
    msg: "{{ login.json.load_balancer_dns_name }}"
    verbosity: 2
