---
- name: get info NC2
  hosts: all
  gather_facts: true
  vars:
    HIBERNATECLUSTER: false
    DOMAIN: "api-gateway-prod.frame.nutanix.com"
    etime: "{{ ansible_date_time.epoch }}"
    api_url_v1: "https://{{ DOMAIN }}/v1"
    qretries: 60
    qdelay: 60
    managevm: true
    update_prism_admin_str: 'dpp/data/nutanix/prism/central:username'
    update_prism_password_str: 'dpp/data/nutanix/prism/central:password'
    update_nc2_client_id_str: 'dpp/data/nutanix/nc2/{{ env }}:CLIENT_ID'
    update_nc2_client_secret_str: 'dpp/data/nutanix/nc2/{{ env }}:CLIENT_SECRET'
    update_nc2_cluster_id_str: 'dpp/data/nutanix/nc2/{{ env }}:CLUSTER_ID'
    hv_credential_string: "auth_method=approle url={{ hvurl }} role_id={{ dpp_hcv_role_id }} secret_id={{ dpp_hcv_secret_id }}"
    hvurl: "{{ lookup('env', 'ANSIBLE_HASHI_VAULT_ADDR') }}"
    dpp_hcv_role_id: "{{ lookup('env', 'ANSIBLE_HASHI_VAULT_ROLE_ID') }}"
    dpp_hcv_secret_id: "{{ lookup('env', 'ANSIBLE_HASHI_VAULT_SECRET_ID') }}"

  pre_tasks:

    - name: Set facts
      ansible.builtin.set_fact:
        prism_user: "{{ lookup('community.general.hashi_vault',  update_prism_admin_str + ' ' + hv_credential_string ) }}"
        prism_password: "{{ lookup('community.general.hashi_vault',  update_prism_password_str + ' ' + hv_credential_string) }}"
        CLIENT_ID: "{{ lookup('community.general.hashi_vault',  update_nc2_client_id_str + ' ' + hv_credential_string) }}"
        CLIENT_SECRET: "{{ lookup('community.general.hashi_vault',  update_nc2_client_secret_str + ' ' + hv_credential_string) }}"
        CLUSTER_ID: "{{ lookup('community.general.hashi_vault',  update_nc2_cluster_id_str + ' ' + hv_credential_string) }}"
      no_log: true
      delegate_to: localhost

    - name: Get cluster current state 
      include_tasks: clusterinfo.yml

  tasks:


#    - name: set url
#      set_fact:
#        api_url_v2: "https://{{ login.json.cluster_service_ip }}:9440/api/nutanix/v2.0/vms"
#        api_url_v3: "https://{{ login.json.cluster_service_ip }}:9440/api/nutanix/v2.0/tasks"
##        api_url_v2: "https://{{ login.json.load_balancer_dns_name }}:9440/api/nutanix/v2.0/vms"
##        api_url_v3: "https://{{ login.json.load_balancer_dns_name }}:9440/api/nutanix/v2.0/tasks"
        


    - name: query Prism Central VM
      include_tasks: vminfocount.yml
